CustomItem:
    #You can find all material you can use here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Type: "EMERALD"
    Name: "NpcReward &7(Right-Clic)"
    Lore:
     - "&cCustom lore 1"
     - "&6Custom lore 2"
     - "&7Etc..."

# You can choose : BLACKSMITH - BUTCHER - FARMER - LIBRARIAN - PRIEST
NpcType: "BLACKSMITH"

# /!\ Don't set same names !
CustomNames:
    name1: "&6Steve"
    name2: "&6Zaral"
    name3: "&6Notch"
    name4: "&6Kim"

MaxPick: 3
DamageEnabledOnStage: false
BlockOnGroundID: '168:1'
Use2block: true
PercentOfSecondBlock: 40
SecondBlockID: '168:2'


